server:
  port: 9070
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    # Eureka服务端不需要向Eureka服务注册
    register-with-eureka: true
    # 不在本地缓存注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
#    com.optimagrowth: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.netflix.eureka: DEBUG  # 如果使用Eureka作为服务发现