spring:
  application:
    name: gateway-server
  profiles:
    active: local
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
