server:
  port: 9090
spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false
    template-loader-path: classpath:/templates/
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # 禁用 Ribbon 负载均衡
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    # Eureka服务端不需要向Eureka服务注册
    register-with-eureka: true
    # 不在本地缓存注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5  # 同步注册表时的等待时间
    enable-self-preservation: false
    peer-eureka-nodes:
      - http://localhost:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "health,info,eureka"
