spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pengliangzhang/spring-cloud.git
          default-label: main
          search-paths:
            - configserver/src/main/resources/configs/
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

server:
  port: 9080

logging:
  level:
    org.springframework.cloud: DEBUG

encrypt:
  key: ${ENCRYPT_KEY}
