spring:
  application:
    name: licensing-service
  datasource:
    url: jdbc:mysql://localhost:3306/licensing-service
    username: user
    password: password

logging:
  level:
    org.springframework.cloud: DEBUG
